import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Providers } from "./providers";
import { ToastContainer } from "react-toastify";
import { ThemeProvider } from "@/components/ui/theme-provider";
import LayoutWrapper from "@/components/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <LayoutWrapper authRequired={true}>
              <Navbar />
              <main className="min-h-screen">{children}</main>
              <Footer />
            </LayoutWrapper>
            <ToastContainer />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
